<?php
$strings = array(

	//Cabecera
	'logueado' => 'Conectado como',
	'principal' => 'Principal',
	'desconectarse' => 'Desconectarse',
	'español' => 'Español',
	'gallego' => 'Gallego',

	//Titulos
	'principal' => 'Principal',
	'titulo añadir controlador' => 'Añadir funcionalidad',
	'titulo borrar controlador' => 'Borrar funcionalidad',
	'titulo editar controlador' => 'Editar funcionalidad',
	'titulo listar controlador' => 'Ver funcionalidades',
	'titulo añadir grupo' => 'Añadir perfil',
	'titulo borrar grupo' => 'Borrar perfil',
	'titulo editar grupo' => 'Editar perfil',
	'titulo listar grupo' => 'Ver perfil',
	'titulo añadir permiso' => 'Añadir permiso',
	'titulo borrar permiso' => 'Borrar permiso',
	'titulo editar permiso' => 'Editar permiso',
	'titulo listar permiso' => 'Ver permiso',
	'titulo añadir usuario' => 'Añadir usuario',
	'titulo borrar usuario' => 'Borrar usuario',
	'titulo editar usuario' => 'Editar usuario',
	'titulo listar usuario' => 'Ver usuarios',
	'titulo añadir cliente' => 'Añadir cliente',
	'titulo borrar cliente' => 'Borrar cliente',
	'titulo editar cliente' => 'Editar cliente',
	'titulo listar cliente' => 'Ver clientes',
	'titulo añadir servicio' => 'Añadir servicio',
	'titulo borrar servicio' => 'Borrar servicio',
	'titulo editar servicio' => 'Editar servicio',
	'titulo listar servicio' => 'Ver servicio',
	'titulo añadir trabajador' => 'Añadir trabajador',
	'titulo borrar trabajador' => 'Borrar trabajador',
	'titulo editar trabajador' => 'Editar trabajador',
	'titulo listar trabajador' => 'Ver trabajador',
	'gestionarTrabajadores' => 'TRABAJADORES',
	'altaTrabajador' => 'Añadir trabajador',
	'bajaTrabajador' => 'Borrar trabajador',
	'modificarTrabajador' => 'Modificar trabajador',
	'consultarTrabajador' => 'Ver trabajadores',
	'buscarTrabajador' => 'Buscar trabajador',
	


	//Menu
	'menu' => 'Menú',
	'gestionarControladores' => 'FUNCIONALIDADES',
	'altaControlador' => 'Añadir controlador',
	'altaAccion' => 'Añadir acción',
	'bajaControlador' => 'Borrar funcionalidad',
	'modificarControlador' => 'Modificar funcionalidad',
	'consultarControlador' => 'Ver funcionalidades',
	'gestionarPermisos' => 'PERMISOS',
	'altaPermiso' => 'Añadir permiso perfil',
	'bajaPermiso' => 'Borrar permiso perfil',
	'modificarPermiso' => 'Modificar permiso perfil',
	'consultarPermiso' => 'Ver permisos perfiles',
	'gestionarGrupos' => 'PERFILES',
	'altaGrupo' => 'Añadir perfil',
	'bajaGrupo' => 'Borrar perfil',
	'modificarGrupo' => 'Modificar perfil',
	'consultarGrupo' => 'Ver perfiles',
	'gestionarUsuario' => 'USUARIOS',
	'altaUsuario' => 'Añadir usuario',
	'bajaUsuario' => 'Borrar usuario',
	'modificarUsuario' => 'Modificar usuario',
	'consultarUsuario' => 'Ver usuarios',
	'buscarUsuario' => 'Buscar usuario',
	'buscarFuncionalidad' => 'Buscar funcionalidad',
	'buscarPermiso' => 'Buscar permiso',
	'buscarCliente' => 'Buscar cliente',
	'gestionarCliente' => 'CLIENTE',
	'altaCliente' => 'Añadir cliente perfil',
	'bajaCliente' => 'Borrar cliente perfil',
	'modificarCliente' => 'Modificar cliente perfil',
	'consultarClientes' => 'Ver clientes perfil',
	'gestionarServicio' => 'SERVICIO',
	'altaServicio' => 'Añadir servicio perfil',
	'bajaServicio' => 'Borrar servicio perfil',
	'modificarServicio' => 'Modificar servicio perfil',
	'consultarServicio' => 'Ver servicios perfil',
	'buscarServicio' => 'Buscar Servicio',

	//Ventanas y botones comunes
	'confirmar borrado' => '¿Confirmar borrado?',
	'confirmar modificacion' => '¿Confirmar modificación?',
	'añadir permisos' => '¿Añadir todos los permisos del controlador?',
	'crear' => 'Añadir',
	'modificar' => 'Modificar',
	'resetear' => 'Resetear',
	'borrar' => 'Borrar',
	'nuevos datos' => 'Nuevos datos',
	'buscar' => 'Buscar',

	//Errores formularios
	'error accion' => '>3-30 letras, una palabra',
	'error controlador' => '4-30 letras, una palabra',
	'error grupo' => '>4-30 letras',
	'error usuario' => '4-16 alfanuméricos',
	'error password' => '4-16 alfanuméricos',
	'error dni' => 'Formato DNI inválido',
	'error letra dni' => 'Letra DNI inválida',
	'error nombre' => '2-30 letras',
	'error apellidos' => '2-30 letras',
	'error telefono' => '999999999',
	'error email' => 'abc@abc.com',
	'error id_cliente' => '4-16 alfanuméricos',
	'error tlf' => '9 números',
	'error direccion' => '4-50 alfanuméricos',
	'error precio' => '19,99',


	//Opciones vistas controlador
	'nuevo controlador' => 'NUEVA FUNCIONALIDAD',
	'buscar controlador' => 'BUSCAR FUNCIONALIDAD',
	'borrar controlador' => 'BORRAR FUNCIONALIDAD',
	'editar controlador' => 'MODIFICAR FUNCIONALIDAD',
	'ver controlador' => 'VER FUNCIONALIDADES',
	'acciones por defecto' => 'Se añaden por defecto las acciones:<br>Add, Delete, Edit, Show y List',
	'controlador' => 'Controlador',
	'controladores registrados' => 'Consultar controladores registrados',
	'accion' => 'Acción',

	//Opciones vistas grupo
	'nuevo grupo' => 'NUEVO PERFIL',
	'borrar grupo' => 'BORRAR PERFIL',
	'editar grupo' => 'MODIFICAR PERFIL',
	'ver grupo' => 'VER PERFILES',
	'grupo' => 'Perfil',

	//Opciones vistas permisos
	'nuevo permiso' => 'NUEVO PERMISO',
	'buscar permiso' => 'BUSCAR PERMISOS',
	'borrar permiso' => 'BORRAR PERMISO',
	'editar permiso' => 'MODIFICAR PERMISO',
	'ver permiso' => 'VER PERMISOS',
	'añadir todo' => 'Añadir todas las acciones del controlador',
	'grupo seleccionado' => 'Perfil seleccionado',
	'accion seleccionada' => 'Acción seleccionada',
	'borrar todos permisos' => 'Borrar permisos sobre controlador',
	'siguiente' => 'Siguiente',

	//Opciones vistas usuarios
	'nuevo usuario' => 'NUEVO USUARIO',
	'buscar usuario' => 'BUSCAR USUARIO',
	'borrar usuario' => 'BORRAR USUARIO',
	'editar usuario' => 'MODIFICAR USUARIO',
	'ver usuario' => 'VER USUARIOS',
	'dni' => 'DNI',
	'campos modificar' => '(rellenar solo campos a modificar)',
	'password' => 'Contraseña',
	'usuario' => 'Usuario',
	'nombre' => 'Nombre',
	'apellidos' => 'Apellidos',
	'telefono' => 'Teléfono',
	'email' => 'Email',
	'dni opcional' => 'DNI trabajador (opcional)',

	
	//Opciones vistas trabajadores
	'buscar trabajador' => 'BUSCAR TRABAJADOR',
	'dni trabajador' => 'DNI del trabajador',
	'nombre' => 'Nombre',
	'apellidos' => 'Apellidos',
	'nuevo trabajador' => 'NUEVO TRABAJADOR',
	'buscar trabajador' => 'BUSCAR TRABAJADOR',
	'borrar trabajador' => 'BORRAR TRABAJADOR',
	'editar trabajador' => 'MODIFICAR TRABAJADOR',
	'ver trabajadores' => 'VER TRABAJADORES',
	'fotoperfil' => 'Foto de perfil',
	'direccion' => 'Dirección',
	'email' => 'Email',
	'fechanac' => 'Fecha de nacimiento',
	'dni' => 'DNI',
	'tipoemp' => 'Tipo de empleado',
	'observaciones' => 'Observaciones',
	'numerocuenta' => 'Número de cuenta',
	'horasextra' => 'Horas extra',
	'externo' => 'Externo',
	'trabajador' => 'Trabajador',
	'administrador' => 'Administrador',
	'monitor' => 'Monitor',
	'secretario' => 'Secretaría',
	'cafeteria' => 'Cafetería',
	'limpieza' => 'Limpieza',
	'otros' => 'Otros',
	'fisioterapeuta' => 'Fisioterapeuta',
	'telefono' => 'Teléfono',
	
	
	
	
	//Opciones vistas cliente
	'nuevo cliente' => 'NUEVO CLIENTE',
	'borrar cliente' => 'BORRAR CLIENTE',
	'editar cliente' => 'EDITAR CLIENTE',
	'ver cliente' => 'VER CLIENTES',
	'buscar cliente' => 'BUSCAR CLIENTE',
	'cliente' => 'CLIENTE',
	'id_cliente' => 'Id Cliente',
	'tlf' => 'Tlf',
	'direccion' => 'Direccion',
	'empty' => 'Campos Vacios',

	//Opciones vistas servicio
	'nuevo servicio' => 'NUEVO SERVICIO',
	'borrar servicio' => 'BORRAR SERVICIO',
	'editar servicio' => 'EDITAR SERVICIO',
	'ver servicio' => 'VER SERVICIOS',
	'buscar servicio' => 'BUSCAR SERVICIO',
	'servicioservicio' => 'SERVICIO',
	'id_servicio' => 'Id Servicio',
	'precio' => 'Precio',
	'descripcion' => 'Descripcion',
	'id_trabajador' => 'Dni Trabajador',
	'servicio' => 'Servicio',


	//Modelos
	'añadido exito' => 'Elemento añadido con éxito.',
	'borrado exito' => 'Elemento eliminado con éxito.',
	'modificacion exito' => 'Elemento modificado con éxito.',
	'ya existe' => '¡El elemento ya existe!',
	'error borrado' => 'ERROR al eliminar.',
	'error modificacion' => 'ERROR al modificar.',
	'dni invalido' => 'El DNI del trabajador no existe.',
	'dni asignado' => 'El DNI del trabajador ya está asignado.',
	'IdC asignado' => 'El id del cliente ya está asignado',
	'Id invalido' => 'El id del cliente no existe',
	
	///////////////// ET2 Iago /////////////////////////////
	
	//Modelos
	'factura sin cerrar' => 'Ya hay una factura sin cerrar de este cliente.',
	'error insertar pago' => 'No hay suficientes ingresos.',
	'no hay' => 'No hay elementos a mostrar.',
	'error caja' => 'ERROR: Balance de caja negativo.',
	
	//Menu
	'caja' => 'CAJA',
	'añadir movimiento' => 'Añadir movimiento',
	'gestionar caja' => 'Gestionar caja',
	'ver movimientos' => 'Ver movimientos',
	
	//Titulos
	'facturas' => 'FACTURAS',
	'titulo crear factura' => 'Crear factura',
	'titulo modificar factura' => 'Modificar factura',
	'titulo gestionar factura' => 'Gestionar facturas<br>cliente',
	'titulo gestionar factura2' => 'Gestionar facturas cliente',
	'titulo buscar facturas' => 'Buscar facturas',
	'titulo ver facturas' => 'Ver facturas cobradas',
	'titulo crear linea' => 'Crear linea',
	'titulo editar linea' => 'Editar linea',
	'titulo añadir movimiento' => 'Crear movimiento caja',
	'titulo editar movimiento' => 'Editar movimiento caja',
	'titulo consultar movimiento' => 'Consultar movimientos caja',
	'titulo listar movimiento' => 'Ver movimientos caja',
	
	//Cabecera
	'menu añadir movimiento' => 'Crear movimiento<br>caja',
	'crear factura' => 'NUEVA FACTURA',
	'modificar factura' => 'EDITAR FACTURA',
	'gestionar factura' => 'GESTIONAR FACTURA',
	'buscar facturas' => 'BUSCAR FACTURAS DEL CLIENTE',
	'ver facturas' => 'VER FACTURAS',
	'crear linea' => 'NUEVA LINEA DE FACTURA',
	'editar linea' => 'EDITAR LINEA DE FACTURA',
	'gestionar linea' => 'GESTIONAR LINEAS DE FACTURA',
	'añadir movimiento' => 'AÑADIR MOVIMIENTO',
	'editar movimiento' => 'EDITAR MOVIMIENTO',
	'consultar movimiento' => 'CONSULTAR MOVIMIENTOS',
	'listar movimiento' => 'VER MOVIMIENTOS',
	'buscar movimiento' => 'BUSCAR MOVIMIENTOS',
	
	//Error formularios
	'error importe caja' => '3 cifras max con decimales',
	'error nombre servicio' => '2-30 letras',
	'error importe linea' => '3 cifras max con decimales',
	'error nombre cliente' => '2-30 letras',
	'error total factura' => '3 cifras max con decimales',
	
	//Vistas caja
	'tipo movimiento' => 'Tipo de movimiento',
	'comentario opcional' => 'Comentario (opcional)',
	'comentario' => 'Comentario',
	'importe caja' => 'Importe en euros',
	'todos' => 'Todos',
	'fecha caja' => 'Fecha',
	'ingreso caja' => 'Ingreso',
	'pago caja' => 'Pago',
	'mes' => '<b>Mes</b>',
	'total caja' => 'Efectivo en caja',
	
	//Vistas factura
	'id factura' => 'ID Factura',
	'nombre cliente' => 'Nombre cliente',
	'cliente' => 'Cliente',
	'fecha cierre' => 'Fecha cierre',
	'fecha cobro' => 'Fecha cobro',
	'factura cobrada' => 'Cobrada',
	'total factura' => 'Total',
	'todas' => 'Todas',
	'no cobrada' => 'No',
	'cobrada' => 'Si',
	'formato fecha invalido' => 'Formato de fecha inválido',
	'fecha invalida' => 'Fecha incorrecta',
	'consultar' => 'Consultar',
	'tipo cobro factura' => 'Tipo de cobro',
	'efectivo' => 'Efectivo',
	'domiciliacion' => 'Domiciliación',
	'tpv' => 'TPV',
	'confirmar cobro' => '¿Confirmar cobro?',
	'cobrar' => 'Cobrar',
	'consultar' => 'Consultar',
	'generar factura' => 'Generar PDF',
	
	//Vistas linea factura
	'numero linea' => 'Nº linea',
	'nombre servicio' => 'Nombre servicio',
	'servicio' => 'Servicio',
	'importe' => 'Importe',
	'descripcion' => 'Descripción (opcional)',
	'descripcion2' => 'Descripción',
	
	///////////////////////////////
)
?>
