<?php
$strings = array(

	//Cabecera
	'logueado' => 'Conectado como',
	'principal' => 'Principal',
	'desconectarse' => 'Desconectarse',
	'español' => 'Castelán',
	'gallego' => 'Galego',

	//Titulos
	'principal' => 'Principal',
	'titulo añadir controlador' => 'Engadir funcionalidade',
	'titulo borrar controlador' => 'Eliminar funcionalidade',
	'titulo editar controlador' => 'Modificar funcionalidade',
	'titulo listar controlador' => 'Ver funcionalidades',
	'titulo añadir grupo' => 'Engadir perfil',
	'titulo borrar grupo' => 'Eliminar perfil',
	'titulo editar grupo' => 'Editar perfil',
	'titulo listar grupo' => 'Ver perfil',
	'titulo añadir permiso' => 'Engadir permiso',
	'titulo borrar permiso' => 'Eliminar permiso',
	'titulo editar permiso' => 'Editar permiso',
	'titulo listar permiso' => 'Ver permiso',
	'titulo añadir usuario' => 'Engadir usuario',
	'titulo borrar usuario' => 'Eliminar usuario',
	'titulo editar usuario' => 'Editar usuario',
	'titulo listar usuario' => 'Ver usuarios',
	'titulo añadir cliente' => 'Engadir cliente',
	'titulo borrar cliente' => 'Eliminar cliente',
	'titulo editar cliente' => 'Editar cliente',
	'titulo listar cliente' => 'Ver clientes',
	'titulo añadir servicio' => 'Engadir servicio',
	'titulo borrar servicio' => 'Borrar servicio',
	'titulo editar servicio' => 'Editar servicio',
	'titulo listar servicio' => 'Ver servicio',

	//Menu
	'menu' => 'Menu',
	'gestionarControladores' => 'FUNCIONALIDADES',
	'altaControlador' => 'Engadir controlador',
	'altaAccion' => 'Engadir acción',
	'bajaControlador' => 'Eliminar funcionalidade',
	'modificarControlador' => 'Modificar funcionalidade',
	'consultarControlador' => 'Ver funcionalidades',
	'gestionarPermisos' => 'PERMISOS',
	'altaPermiso' => 'Engadir permiso perfil',
	'bajaPermiso' => 'Eliminar permiso perfil',
	'modificarPermiso' => 'Modificar permiso perfil',
	'consultarPermiso' => 'Ver permisos perfís',
	'gestionarGrupos' => 'PERFÍS',
	'altaGrupo' => 'Engadir perfil',
	'bajaGrupo' => 'Eliminar perfil',
	'modificarGrupo' => 'Modificar perfil',
	'consultarGrupo' => 'Ver perfís',
	'gestionarUsuario' => 'USUARIOS',
	'altaUsuario' => 'Engadir usuario',
	'bajaUsuario' => 'Eliminar usuario',
	'modificarUsuario' => 'Modificar usuario',
	'consultarUsuario' => 'Ver usuarios',
	'buscarUsuario' => 'Buscar usuario',
	'buscarFuncionalidad' => 'Buscar funcionalidade',
	'buscarPermiso' => 'Buscar permiso',
	'buscarCliente' => 'Buscar cliente',
	'gestionarCliente' => 'CLIENTE',
	'altaCliente' => 'Engadir cliente perfil',
	'bajaCliente' => 'Borrar cliente perfil',
	'modificarCliente' => 'Modificar cliente perfil',
	'consultarClientes' => 'Ver clientes perfil',
	'gestionarServicio' => 'SERVICIO',
	'altaServicio' => 'Engadir servicio perfil',
	'bajaServicio' => 'Borrar servicio perfil',
	'modificarServicio' => 'Modificar servicio perfil',
	'consultarServicio' => 'Ver servicios perfil',
	'buscarServicio' => 'Buscar Servicio',

	//Ventanas y botones comunes
	'confirmar borrado' => '¿Confirmar borrado?',
	'confirmar modificacion' => '¿Confirmar modificacion?',
	'añadir permisos' => '¿Engadir todos os permisos do controlador?',
	'crear' => 'Engadir',
	'modificar' => 'Modificar',
	'resetear' => 'Resetear',
	'borrar' => 'Eliminar',
	'nuevos datos' => 'Novos datos',
	'buscar' => 'Buscar',

	//Errores formularios
	'error accion' => '>3-30 letras, unha palabra',
	'error controlador' => '4-30 letras, unha palabra',
	'error grupo' => '>4-30 letras',
	'error usuario' => '4-16 alfanuméricos',
	'error password' => '4-16 alfanuméricos',
	'error dni' => 'Formato DNI inválido',
	'error letra dni' => 'Letra DNI inválida',
	'error nombre' => '2-30 letras',
	'error apellidos' => '2-30 letras',
	'error telefono' => '999999999',
	'error email' => 'abc@abc.com',
	'error id_cliente' => '4-16 alfanuméricos',
	'error tlf' => '9 números',
	'error direccion' => '4-50 alfanuméricos',
	'error precio' => '19,99',

	//Opciones vistas controlador
	'nuevo controlador' => 'NOVA FUNCIONALIDADE',
	'buscar controlador' => 'BUSCAR FUNCIONALIDADE',
	'borrar controlador' => 'ELIMINAR FUNCIONALIDADE',
	'editar controlador' => 'MODIFICAR FUNCIONALIDADE',
	'ver controlador' => 'VER FUNCIONALIDADES',
	'acciones por defecto' => 'Engádense por defecto as accións:<br>Add, Delete, Edit, Show y List',
	'controlador' => 'Controlador',
	'controladores registrados' => 'Consultar controladores rexistrados',
	'accion' => 'Acción',

	//Opciones vistas grupo
	'nuevo grupo' => 'NOVO PERFIL',
	'borrar grupo' => 'ELIMINAR PERFIL',
	'editar grupo' => 'MODIFICAR PERFIL',
	'ver grupo' => 'VER PERFÍS',
	'grupo' => 'Perfil',

	//Opciones vistas servicio
	'nuevo servicio' => 'NOVO SERVIZO',
	'borrar servicio' => 'BORRAR SERVIZO',
	'editar servicio' => 'EDITAR SERVIZO',
	'ver servicio' => 'VER SERVIZOS',
	'buscar servicio' => 'BUSCAR SERVIZO',
	'servicioservicio' => 'SERVIZO',
	'id_servicio' => 'Id Servicio',
	'descripcion' => 'Descripcion',
	'id_trabajador' => 'Dni Trabajador',
	'servicio' => 'Servizo',

	//Opciones vistas permisos
	'nuevo permiso' => 'NOVO PERMISO',
	'buscar permiso' => 'BUSCAR PERMISOS',
	'borrar permiso' => 'ELIMINAR PERMISO',
	'editar permiso' => 'MODIFICAR PERMISO',
	'ver permiso' => 'VER PERMISOS',
	'añadir todo' => 'Engadir todas as accións do controlador',
	'grupo seleccionado' => 'Perfil seleccionado',
	'accion seleccionada' => 'Acción seleccionada',
	'borrar todos permisos' => 'Eliminar permisos sobre controlador',
	'siguiente' => 'Seguinte',

	//Opciones vistas usuarios
	'nuevo usuario' => 'NOVO USUARIO',
	'buscar usuario' => 'BUSCAR USUARIO',
	'borrar usuario' => 'ELIMINAR USUARIO',
	'editar usuario' => 'MODIFICAR USUARIO',
	'ver usuario' => 'VER USUARIOS',
	'campos modificar' => '(cubrir soamente campos a modificar)',
	'dni' => 'DNI',
	'password' => 'Contrasinal',
	'usuario' => 'Usuario',
	'nombre' => 'Nome',
	'apellidos' => 'Apelidos',
	'telefono' => 'Teléfono',
	'email' => 'Email',
	'dni opcional' => 'DNI traballador (opcional)',

	//Opciones vistas clientes
	'nuevo cliente' => 'NOVO CLIENTE',
	'borrar cliente' => 'ELIMINAR CLIENTE',
	'editar cliente' => 'EDITAR CLIENTE',
	'ver cliente' => 'VER CLIENTES',
	'buscar cliente' => 'BUSCAR CLIENTE',
	'cliente' => 'CLIENTE',
	'id_cliente' => 'Id Cliente',
	'tlf' => 'Tlf',
	'direccion' => 'Direccion',
	'empty' => 'Campos Baleiros',
	'precio' => 'Prezo',


	//Modelos
	'añadido exito' => 'Elemento engadido con éxito.',
	'borrado exito' => 'Elemento eliminado con éxito.',
	'modificacion exito' => 'Elemento modificado con éxito.',
	'ya existe' => '¡O elemento xa existe!',
	'error borrado' => 'ERRO ó eliminar.',
	'error modificacion' => 'ERRO ó modificar elemento.',
	'dni invalido' => 'O DNI do traballador non existe.',
	'dni asignado' => 'O DNI do traballador xa está asignado.',
	'IdC asignado' => 'O id do cliente xa está asignado',
	'Id invalido' => 'El id del cliente no existe',
	
	///////////////// ET2 Iago /////////////////////////////
	
	//Modelos
	'factura sin cerrar' => 'Xa hai unha factura sen cerrar deste cliente.',
	'error insertar pago' => 'Non hai suficientes ingresos.',
	'no hay' => 'Non hai elementos a mostrar.',
	'error caja' => 'ERRO: Balance de caixa negativo.',
	
	//Menu
	'caja' => 'CAIXA',
	'añadir movimiento' => 'Engador movemento',
	'gestionar caja' => 'Xestionar caixa',
	'ver movimientos' => 'Ver movementos',
	
	//Titulos
	'facturas' => 'FACTURAS',
	'titulo crear factura' => 'Crear factura',
	'titulo modificar factura' => 'Modificar factura',
	'titulo gestionar factura' => 'Xestionar facturas<br>cliente',
	'titulo gestionar factura2' => 'Xestionar facturas cliente',
	'titulo buscar facturas' => 'Buscar facturas',
	'titulo ver facturas' => 'Ver facturas cobradas',
	'titulo crear linea' => 'Crear liña',
	'titulo editar linea' => 'Editar liña',
	'titulo añadir movimiento' => 'Crear movemento caixa',
	'titulo editar movimiento' => 'Editar movemento caixa',
	'titulo consultar movimiento' => 'Consultar movementos caixa',
	'titulo listar movimiento' => 'Ver movementos caixa',
	
	//Cabecera
	'menu añadir movimiento' => 'Crear movemento<br>caixa',
	'crear factura' => 'NOVA FACTURA',
	'modificar factura' => 'EDITAR FACTURA',
	'gestionar factura' => 'XESTIONAR FACTURA',
	'buscar facturas' => 'BUSCAR FACTURAS DO CLIENTE',
	'ver facturas' => 'VER FACTURAS',
	'crear linea' => 'NOVA LIÑA DE FACTURA',
	'editar linea' => 'EDITAR LIÑA DE FACTURA',
	'gestionar linea' => 'XESTIONAR LIÑAS DE FACTURA',
	'añadir movimiento' => 'ENGADIR MOVEMENTO',
	'editar movimiento' => 'EDITAR MOVEMENTO',
	'consultar movimiento' => 'CONSULTAR MOVEMENTOS',
	'listar movimiento' => 'VER MOVEMENTOS',
	'buscar movimiento' => 'BUSCAR MOVEMENTOS',
	
	//Error formularios
	'error importe caja' => '3 cifras max con decimales',
	'error nombre servicio' => '2-30 letras',
	'error importe linea' => '3 cifras max con decimales',
	'error nombre cliente' => '2-30 letras',
	'error total factura' => '3 cifras max con decimales',
	
	//Vistas caja
	'tipo movimiento' => 'Tipo de movemento',
	'comentario opcional' => 'Comentario (opcional)',
	'comentario' => 'Comentario',
	'importe caja' => 'Importe en euros',
	'fecha caja' => 'Data',
	'todos' => 'Todos',
	'mes' => '<b>Mes</b>',
	'ingreso caja' => 'Ingreso',
	'pago caja' => 'Pago',
	'total caja' => 'Efectivo en caixa',
	
	//Vistas factura
	'id factura' => 'ID Factura',
	'nombre cliente' => 'Nome cliente',
	'cliente' => 'Cliente',
	'fecha cierre' => 'Data de peche',
	'fecha cobro' => 'Data cobro',
	'factura cobrada' => 'Cobrada',
	'total factura' => 'Total',
	'todas' => 'Todas',
	'no cobrada' => 'Non',
	'cobrada' => 'Si',
	'formato fecha invalido' => 'Formato de data incorrecto',
	'fecha invalida' => 'Data incorrecta',
	'consultar' => 'Consultar',
	'tipo cobro factura' => 'Tipo de cobro',
	'efectivo' => 'Efectivo',
	'domiciliacion' => 'Domiciliación',
	'tpv' => 'TPV',
	'confirmar cobro' => 'Confirmar cobro?',
	'cobrar' => 'Cobrar',
	'consultar' => 'Consultar',
	'generar factura' => 'Xerar PDF',
	
	//Vistas linea factura
	'numero linea' => 'Nº liña',
	'servicio' => 'Servicio',
	'nombre servicio' => 'Nome servicio',
	'importe' => 'Importe',
	'descripcion' => 'Descripción (opcional)',
	'descripcion2' => 'Descripción',
	
	///////////////////////////////
)
?>
