<?php
$strings = array(

	//Cabecera
	'logueado' => 'Conectado como',
	'principal' => 'Principal',
	'desconectarse' => 'Desconectarse',
	'español' => 'Español',
	'gallego' => 'Gallego',

	//Titulos
	'principal' => 'Principal',
	'titulo añadir controlador' => 'Añadir funcionalidad',
	'titulo borrar controlador' => 'Borrar funcionalidad',
	'titulo editar controlador' => 'Editar funcionalidad',
	'titulo listar controlador' => 'Ver funcionalidades',
	'titulo añadir grupo' => 'Añadir perfil',
	'titulo borrar grupo' => 'Borrar perfil',
	'titulo editar grupo' => 'Editar perfil',
	'titulo listar grupo' => 'Ver perfil',
	'titulo añadir permiso' => 'Añadir permiso',
	'titulo borrar permiso' => 'Borrar permiso',
	'titulo editar permiso' => 'Editar permiso',
	'titulo listar permiso' => 'Ver permiso',
	'titulo añadir usuario' => 'Añadir usuario',
	'titulo borrar usuario' => 'Borrar usuario',
	'titulo editar usuario' => 'Editar usuario',
	'titulo listar usuario' => 'Ver usuarios',
	'titulo añadir cliente' => 'Añadir cliente',
	'titulo borrar cliente' => 'Borrar cliente',
	'titulo editar cliente' => 'Editar cliente',

	//Menu
	'menu' => 'Menú',
	'gestionarControladores' => 'FUNCIONALIDADES',
	'altaControlador' => 'Añadir controlador',
	'altaAccion' => 'Añadir acción',
	'bajaControlador' => 'Borrar funcionalidad',
	'modificarControlador' => 'Modificar funcionalidad',
	'consultarControlador' => 'Ver funcionalidades',
	'gestionarPermisos' => 'PERMISOS',
	'altaPermiso' => 'Añadir permiso perfil',
	'bajaPermiso' => 'Borrar permiso perfil',
	'modificarPermiso' => 'Modificar permiso perfil',
	'consultarPermiso' => 'Ver permisos perfiles',
	'gestionarGrupos' => 'PERFILES',
	'altaGrupo' => 'Añadir perfil',
	'bajaGrupo' => 'Borrar perfil',
	'modificarGrupo' => 'Modificar perfil',
	'consultarGrupo' => 'Ver perfiles',
	'gestionarUsuario' => 'USUARIOS',
	'altaUsuario' => 'Añadir usuario',
	'bajaUsuario' => 'Borrar usuario',
	'modificarUsuario' => 'Modificar usuario',
	'consultarUsuario' => 'Ver usuarios',
	'buscarUsuario' => 'Buscar usuario',
	'buscarFuncionalidad' => 'Buscar funcionalidad',
	'buscarPermiso' => 'Buscar permiso',
	'gestionarCliente' => 'CLIENTE',
	'altaCliente' => 'Añadir cliente perfil',
	'bajaCliente' => 'Borrar cliente perfil',
	'modificarCliente' => 'Modificar cliente perfil',
	'consultarClientes' => 'Ver clientes perfil',

	//Ventanas y botones comunes
	'confirmar borrado' => '¿Confirmar borrado?',
	'confirmar modificacion' => '¿Confirmar modificación?',
	'añadir permisos' => '¿Añadir todos los permisos del controlador?',
	'crear' => 'Añadir',
	'modificar' => 'Modificar',
	'resetear' => 'Resetear',
	'borrar' => 'Borrar',
	'nuevos datos' => 'Nuevos datos',
	'buscar' => 'Buscar',

	//Errores formularios
	'error accion' => '>3-30 letras, una palabra',
	'error controlador' => '4-30 letras, una palabra',
	'error grupo' => '>4-30 letras',
	'error usuario' => '4-16 alfanuméricos',
	'error password' => '4-16 alfanuméricos',
	'error dni' => 'Formato DNI inválido',
	'error letra dni' => 'Letra DNI inválida',
	'error nombre' => '2-30 letras',
	'error apellidos' => '2-30 letras',
	'error telefono' => '999999999',
	'error email' => 'abc@abc.com',
	'error id_cliente' => '4-16 alfanuméricos',
	'error tlf' => '9 números',
	'error direccion' => '4-50 alfanuméricos',

	//Opciones vistas controlador
	'nuevo controlador' => 'NUEVA FUNCIONALIDAD',
	'buscar controlador' => 'BUSCAR FUNCIONALIDAD',
	'borrar controlador' => 'BORRAR FUNCIONALIDAD',
	'editar controlador' => 'MODIFICAR FUNCIONALIDAD',
	'ver controlador' => 'VER FUNCIONALIDADES',
	'acciones por defecto' => 'Se añaden por defecto las acciones:<br>Add, Delete, Edit, Show y List',
	'controlador' => 'Controlador',
	'controladores registrados' => 'Consultar controladores registrados',
	'accion' => 'Acción',

	//Opciones vistas grupo
	'nuevo grupo' => 'NUEVO PERFIL',
	'borrar grupo' => 'BORRAR PERFIL',
	'editar grupo' => 'MODIFICAR PERFIL',
	'ver grupo' => 'VER PERFILES',
	'grupo' => 'Perfil',

	//Opciones vistas permisos
	'nuevo permiso' => 'NUEVO PERMISO',
	'buscar permiso' => 'BUSCAR PERMISOS',
	'borrar permiso' => 'BORRAR PERMISO',
	'editar permiso' => 'MODIFICAR PERMISO',
	'ver permiso' => 'VER PERMISOS',
	'añadir todo' => 'Añadir todas las acciones del controlador',
	'grupo seleccionado' => 'Perfil seleccionado',
	'accion seleccionada' => 'Acción seleccionada',
	'borrar todos permisos' => 'Borrar permisos sobre controlador',
	'siguiente' => 'Siguiente',

	//Opciones vistas usuarios
	'nuevo usuario' => 'NUEVO USUARIO',
	'buscar usuario' => 'BUSCAR USUARIO',
	'borrar usuario' => 'BORRAR USUARIO',
	'editar usuario' => 'MODIFICAR USUARIO',
	'ver usuario' => 'VER USUARIOS',
	'dni' => 'DNI',
	'campos modificar' => '(rellenar solo campos a modificar)',
	'password' => 'Contraseña',
	'usuario' => 'Usuario',
	'nombre' => 'Nombre',
	'apellidos' => 'Apellidos',
	'telefono' => 'Teléfono',
	'email' => 'Email',
	'dni opcional' => 'DNI trabajador (opcional)',

	//Opciones vistas cliente
	'nuevo cliente' => 'NUEVO CLIENTE',
	'borrar cliente' => 'BORRAR CLIENTE',
	'editar cliente' => 'EDITAR CLIENTE',
	'ver cliente' => 'VER CLIENTES',
	'cliente' => 'CLIENTE',
	'id_cliente' => 'Id Cliente',
	'tlf' => 'Tlf',
	'direccion' => 'Direccion',
	'empty' => 'Campos Vacios',

	//Modelos
	'añadido exito' => 'Elemento añadido con éxito.',
	'borrado exito' => 'Elemento eliminado con éxito.',
	'modificacion exito' => 'Elemento modificado con éxito.',
	'ya existe' => '¡El elemento ya existe!',
	'error borrado' => 'ERROR al eliminar.',
	'error modificacion' => 'ERROR al modificar.',
	'dni invalido' => 'El DNI del trabajador no existe.',
	'dni asignado' => 'El DNI del trabajador ya está asignado.',
	'IdC asignado' => 'El id del cliente ya está asignado'
)
?>
