<?php
$strings = array(

	//Cabecera
	'logueado' => 'Conectado como',
	'principal' => 'Principal',
	'desconectarse' => 'Desconectarse',
	'español' => 'Castelán',
	'gallego' => 'Galego',

	//Titulos
	'principal' => 'Principal',
	'titulo añadir controlador' => 'Engadir funcionalidade',
	'titulo borrar controlador' => 'Eliminar funcionalidade',
	'titulo editar controlador' => 'Modificar funcionalidade',
	'titulo listar controlador' => 'Ver funcionalidades',
	'titulo añadir grupo' => 'Engadir perfil',
	'titulo borrar grupo' => 'Eliminar perfil',
	'titulo editar grupo' => 'Editar perfil',
	'titulo listar grupo' => 'Ver perfil',
	'titulo añadir permiso' => 'Engadir permiso',
	'titulo borrar permiso' => 'Eliminar permiso',
	'titulo editar permiso' => 'Editar permiso',
	'titulo listar permiso' => 'Ver permiso',
	'titulo añadir usuario' => 'Engadir usuario',
	'titulo borrar usuario' => 'Eliminar usuario',
	'titulo editar usuario' => 'Editar usuario',
	'titulo listar usuario' => 'Ver usuarios',
	'titulo añadir cliente' => 'Engadir cliente',
	'titulo borrar cliente' => 'Eliminar cliente',
	'titulo editar cliente' => 'Editar cliente',
	'titulo listar cliente' => 'Ver clientes',
	'titulo añadir servicio' => 'Engadir servicio',
	'titulo borrar servicio' => 'Borrar servicio',
	'titulo editar servicio' => 'Editar servicio',
	'titulo listar servicio' => 'Ver servicio',

	//Menu
	'menu' => 'Menu',
	'gestionarControladores' => 'FUNCIONALIDADES',
	'altaControlador' => 'Engadir controlador',
	'altaAccion' => 'Engadir acción',
	'bajaControlador' => 'Eliminar funcionalidade',
	'modificarControlador' => 'Modificar funcionalidade',
	'consultarControlador' => 'Ver funcionalidades',
	'gestionarPermisos' => 'PERMISOS',
	'altaPermiso' => 'Engadir permiso perfil',
	'bajaPermiso' => 'Eliminar permiso perfil',
	'modificarPermiso' => 'Modificar permiso perfil',
	'consultarPermiso' => 'Ver permisos perfís',
	'gestionarGrupos' => 'PERFÍS',
	'altaGrupo' => 'Engadir perfil',
	'bajaGrupo' => 'Eliminar perfil',
	'modificarGrupo' => 'Modificar perfil',
	'consultarGrupo' => 'Ver perfís',
	'gestionarUsuario' => 'USUARIOS',
	'altaUsuario' => 'Engadir usuario',
	'bajaUsuario' => 'Eliminar usuario',
	'modificarUsuario' => 'Modificar usuario',
	'consultarUsuario' => 'Ver usuarios',
	'buscarUsuario' => 'Buscar usuario',
	'buscarFuncionalidad' => 'Buscar funcionalidade',
	'buscarPermiso' => 'Buscar permiso',
	'buscarCliente' => 'Buscar cliente',
	'gestionarCliente' => 'CLIENTE',
	'altaCliente' => 'Engadir cliente perfil',
	'bajaCliente' => 'Borrar cliente perfil',
	'modificarCliente' => 'Modificar cliente perfil',
	'consultarClientes' => 'Ver clientes perfil',
	'gestionarServicio' => 'SERVICIO',
	'altaServicio' => 'Engadir servicio perfil',
	'bajaServicio' => 'Borrar servicio perfil',
	'modificarServicio' => 'Modificar servicio perfil',
	'consultarServicio' => 'Ver servicios perfil',
	'buscarServicio' => 'Buscar Servicio',

	//Ventanas y botones comunes
	'confirmar borrado' => '¿Confirmar borrado?',
	'confirmar modificacion' => '¿Confirmar modificacion?',
	'añadir permisos' => '¿Engadir todos os permisos do controlador?',
	'crear' => 'Engadir',
	'modificar' => 'Modificar',
	'resetear' => 'Resetear',
	'borrar' => 'Eliminar',
	'nuevos datos' => 'Novos datos',
	'buscar' => 'Buscar',

	//Errores formularios
	'error accion' => '>3-30 letras, unha palabra',
	'error controlador' => '4-30 letras, unha palabra',
	'error grupo' => '>4-30 letras',
	'error usuario' => '4-16 alfanuméricos',
	'error password' => '4-16 alfanuméricos',
	'error dni' => 'Formato DNI inválido',
	'error letra dni' => 'Letra DNI inválida',
	'error nombre' => '2-30 letras',
	'error apellidos' => '2-30 letras',
	'error telefono' => '999999999',
	'error email' => 'abc@abc.com',
	'error id_cliente' => '4-16 alfanuméricos',
	'error tlf' => '9 números',
	'error direccion' => '4-50 alfanuméricos',
	'error precio' => '19,99',

	//Opciones vistas controlador
	'nuevo controlador' => 'NOVA FUNCIONALIDADE',
	'buscar controlador' => 'BUSCAR FUNCIONALIDADE',
	'borrar controlador' => 'ELIMINAR FUNCIONALIDADE',
	'editar controlador' => 'MODIFICAR FUNCIONALIDADE',
	'ver controlador' => 'VER FUNCIONALIDADES',
	'acciones por defecto' => 'Engádense por defecto as accións:<br>Add, Delete, Edit, Show y List',
	'controlador' => 'Controlador',
	'controladores registrados' => 'Consultar controladores rexistrados',
	'accion' => 'Acción',

	//Opciones vistas grupo
	'nuevo grupo' => 'NOVO PERFIL',
	'borrar grupo' => 'ELIMINAR PERFIL',
	'editar grupo' => 'MODIFICAR PERFIL',
	'ver grupo' => 'VER PERFÍS',
	'grupo' => 'Perfil',

	//Opciones vistas servicio
	'nuevo servicio' => 'NOVO SERVICIO',
	'borrar servicio' => 'BORRAR SERVICIO',
	'editar servicio' => 'EDITAR SERVICIO',
	'ver servicio' => 'VER SERVICIOS',
	'buscar servicio' => 'BUSCAR SERVICIO',
	'servicioservicio' => 'SERVICIO',
	'id_servicio' => 'Id Servicio',
	'descripcion' => 'Descripcion',
	'id_trabajador' => 'Dni Trabajador',

	//Opciones vistas permisos
	'nuevo permiso' => 'NOVO PERMISO',
	'buscar permiso' => 'BUSCAR PERMISOS',
	'borrar permiso' => 'ELIMINAR PERMISO',
	'editar permiso' => 'MODIFICAR PERMISO',
	'ver permiso' => 'VER PERMISOS',
	'añadir todo' => 'Engadir todas as accións do controlador',
	'grupo seleccionado' => 'Perfil seleccionado',
	'accion seleccionada' => 'Acción seleccionada',
	'borrar todos permisos' => 'Eliminar permisos sobre controlador',
	'siguiente' => 'Seguinte',

	//Opciones vistas usuarios
	'nuevo usuario' => 'NOVO USUARIO',
	'buscar usuario' => 'BUSCAR USUARIO',
	'borrar usuario' => 'ELIMINAR USUARIO',
	'editar usuario' => 'MODIFICAR USUARIO',
	'ver usuario' => 'VER USUARIOS',
	'campos modificar' => '(cubrir soamente campos a modificar)',
	'dni' => 'DNI',
	'password' => 'Contrasinal',
	'usuario' => 'Usuario',
	'nombre' => 'Nome',
	'apellidos' => 'Apelidos',
	'telefono' => 'Teléfono',
	'email' => 'Email',
	'dni opcional' => 'DNI traballador (opcional)',

	//Opciones vistas clientes
	'nuevo cliente' => 'NOVO CLIENTE',
	'borrar cliente' => 'ELIMINAR CLIENTE',
	'editar cliente' => 'EDITAR CLIENTE',
	'ver cliente' => 'VER CLIENTES',
	'buscar cliente' => 'BUSCAR CLIENTE',
	'cliente' => 'CLIENTE',
	'id_cliente' => 'Id Cliente',
	'tlf' => 'Tlf',
	'direccion' => 'Direccion',
	'empty' => 'Campos Baleiros',
	'precio' => 'Prezo',


	//Modelos
	'añadido exito' => 'Elemento engadido con éxito.',
	'borrado exito' => 'Elemento eliminado con éxito.',
	'modificacion exito' => 'Elemento modificado con éxito.',
	'ya existe' => '¡O elemento xa existe!',
	'error borrado' => 'ERRO ó eliminar.',
	'error modificacion' => 'ERRO ó modificar elemento.',
	'dni invalido' => 'O DNI do traballador non existe.',
	'dni asignado' => 'O DNI do traballador xa está asignado.',
	'IdC asignado' => 'O id do cliente xa está asignado',
	'Id invalido' => 'El id del cliente no existe'
)
?>
